spring.application.name=hospital-management-system
# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_management_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# H2 Test Database (Commented out)
# spring.datasource.url=jdbc:h2:mem:hospital_db;DB_CLOSE_DELAY=-1
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=user
spring.security.user.password=admin123

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=utkarshpawade9@gmail.com
spring.mail.password=mavg qfwu upqx hetk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true