spring.application.name=hospital-management-system

# MySQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hospital_management_system?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:manager}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Security & CORS Configuration
frontend.url=${FRONTEND_URL:http://localhost:5173}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=user
spring.security.user.password=admin123

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:medicarenotify2003@gmail.com}
spring.mail.password=${MAIL_PASSWORD:qqdvesqiuoamihbn}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

hospital.service.fee=500

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_TLxh0pCseBQt01}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:TZGuJ2xDRU0RJAjDN0gaOuI5}